Recipe App
Chimwemwe-127001/recipe-app pull request #21
Opened 2022-04-15 15:09 UTC by Chimwemwe-127001

>#### In this final milestone, we, as a *dyad(team of two)* completed this project using our *[Kanban Board](https://github.com/Chimwemwe-127001/recipe-app/projects/1)* that was created using the following completed *[issues](https://github.com/Chimwemwe-127001/recipe-app/issues?q=is%3Aissue+is%3Aclosed)* referencing project requirements:

- [x] #1
- [x] #2
- [x] #3 
- [x] #4
- [x] #5 
- [x] #6 
- [x] #7 
- [x] #8 
- [x] #9 
- [x] #10

2022-04-15 22:49 UTC, andersonlebon requested changes
## Hi @Chimwemwe-127001  && @KingsleyIbe 

Good job so far! I know you have worked hard on making this milestone But  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 22:49 UTC, andersonlebon commented on app/controllers/application_controller.rb
> +  end
- [ ] Kindly I think you need to fix this devise error when signing in 

![image](https://user-images.githubusercontent.com/65068771/163635809-0ae463a3-327c-4f0a-9745-b3dcc9a25f3a.png)

2022-04-15 22:49 UTC, andersonlebon commented on app/controllers/foods_controller.rb
> +      redirect_to user_session_path
- [ ] Kindly note that this should display all Food in the database only for the current user.

2022-04-15 22:49 UTC, andersonlebon commented on app/views/foods/index.html.erb
> +            <td class="align-middle"><%= button_to 'Delete', food_url(food), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
- [ ] Kindly a food can be deleted only by its owner. Use [cancan](https://github.com/CanCanCommunity/cancancan) to make authorisation. Hint :point_down: 

```html.erb
<td class="align-middle">

 <% if can? :distroy, food %>

      <%= button_to 'Delete', food_url(food), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %>

  <% else %>

      cannot delete this

  <% end %>
</td>
```

2022-04-15 22:49 UTC, andersonlebon commented on app/controllers/recipe_foods_controller.rb
> +  end
- [ ] Kindly note that the user should select all food from the database when adding ingredients and not only his associated foods. Hint :point_down: 

```rb
  def set_foods
        @foods = Food.includes(:recipe_foods).map { |food| [food.name, food.id] }
  end

2022-04-15 22:49 UTC, andersonlebon commented on app/controllers/application_controller.rb
> +
## [OPTIONAL]

- [ ] Kindly I would suggest you protect your routes by adding this`before_action :authenticate_user!`
 parameter to your App controller. Without this, all your forms are accessible without the user being authenticated

2022-04-15 22:59 UTC, Chimwemwe-127001 commented on app/controllers/application_controller.rb
> +  end
![chrome-capture-2022-3-16](https://user-images.githubusercontent.com/52143815/163650931-e5892387-d99b-4180-bc16-96cf03f32e32.gif)
Its working on my end

2022-04-15 23:09 UTC, Chimwemwe-127001 commented on app/controllers/recipe_foods_controller.rb
> +  end
![FireShot Capture 027 - RecipeApp - 127 0 0 1](https://user-images.githubusercontent.com/52143815/163651322-23c73d35-1053-45a3-97ab-912351343b2d.png)
- Everything is working fine. Your suggested code gets all foods for all users in the database, foods that don't even belong to that particular user.

2022-04-15 23:17 UTC, Chimwemwe-127001 commented on app/views/foods/index.html.erb
> +            <td class="align-middle"><%= button_to 'Delete', food_url(food), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
I used cancancan to make authorisation. This page is unique to every user. Every user has their own foods list. The foods_controller get foods that reference a user in particular. Below you will find two screenshots of two different users
![FireShot Capture 030 - RecipeApp - 127 0 0 1](https://user-images.githubusercontent.com/52143815/163651776-14e44d67-d215-439d-8e45-e3e5b0abf3b9.png)
![FireShot Capture 029 - RecipeApp - 127 0 0 1](https://user-images.githubusercontent.com/52143815/163651778-4033956c-f2a9-491c-b399-7ea63d36cdf2.png)

2022-04-15 23:19 UTC, Chimwemwe-127001 commented on app/controllers/foods_controller.rb
> +      redirect_to user_session_path
Yes, it code does. As the project requirements suggest, we have to solve N + 1 problems. I used `Eager Loading`

2022-04-16 00:46 UTC, andersonlebon commented on app/controllers/application_controller.rb
> +  end
Hello @Chimwemwe-127001  Try to sign Up

2022-04-16 00:52 UTC, Chimwemwe-127001 commented on app/controllers/application_controller.rb
> +  end
- Hello @andersonlebon 
- It's working fine.
- before signing in a user has to be confirmed for signing in, if you check your terminal you will receive a confirmation link

2022-04-16 00:57 UTC, andersonlebon commented on app/controllers/recipe_foods_controller.rb
> +  end
Hello, @Chimwemwe-127001 Kindly note that In this case, it does not need to belong to the current user.

2022-04-16 00:59 UTC, andersonlebon commented on app/controllers/recipe_foods_controller.rb
> +  end
The logic behind the project is to add an ingredient based on whatever is in the database.

2022-04-16 01:08 UTC, andersonlebon commented on app/views/foods/index.html.erb
> +            <td class="align-middle"><%= button_to 'Delete', food_url(food), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
- [ ] Kindly I think for Foods you need to display all foods in the database, not only for the logged-in users. That is what the requirements is trying to say. And then with this, you will see that the authorization is just going to be on the delete button. 

Check this example here I used within your code.

![image](https://user-images.githubusercontent.com/65068771/163655910-74225c22-3c6a-4d7e-90ac-e85abfcc6d1a.png)

The user is able to see all foods in the database but can only delete his own foods

2022-04-16 01:17 UTC, andersonlebon commented on app/controllers/foods_controller.rb
> +      redirect_to user_session_path
Yes, sure :clap:  you solve n+1 queries problems, However, I was talking about displaying All food in the database not only foods for a particular user.

```rb
      @food = Food.includes(:user)
``
Kindly that the requirement did not say to display foods created by the logged-in user :point_down: 

![image](https://user-images.githubusercontent.com/65068771/163656146-0d02ad2a-da24-4492-b679-cd6fb27cf717.png)

Compare that requirement and the requirement where they precise that the `Recipes list` should be for the logged-in user. :point_down: 

![image](https://user-images.githubusercontent.com/65068771/163656221-1ec9a920-5161-4294-a2c5-74cedbaae542.png)

2022-04-16 01:28 UTC, andersonlebon commented on app/controllers/application_controller.rb
> +  end
https://user-images.githubusercontent.com/65068771/163656538-3187f162-b08f-4f24-982d-bf6a4a7b035f.mp4

2022-04-16 01:36 UTC, Chimwemwe-127001 commented on app/controllers/application_controller.rb
> +  end
https://user-images.githubusercontent.com/52143815/163656775-48d99031-2c0c-4e9a-a970-37bcdaace826.mp4

2022-04-16 01:59 UTC, andersonlebon commented on app/controllers/application_controller.rb
> +  end
Okay, that's nice. I have tried this is working. As a suggestion, I would really advise adding Information on how to confirm the account so that the reviewer may know How to test your project. Be, I have to disable the `confirmable` devise parameter in order to proceed with your review. Thanks for this.

2022-04-16 09:46 UTC, Davidosky007 reviewed
Hello @Chimwemwe-127001  👋,

_This is an additional review as a result of the second opinion request._

Well done with all the progress you have made so far 💪👏 

- I can see there is a slight difference between the Code reviewers guideline and the Project requirement we would work on that shortly 🙏 
- Good job implementing all the project requirements 👏 as i can see all requested changes by the reviewer as per the project requirements works properly as expected 👍 
- [OPTIONAL] I would suggest you add the shopping list index page to your navigation menu this is a requirement [Check here ](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#:~:text=Create%20navigation%20menu%20that%20allows%20users%20to%20open%20all%20of%20the%20pages%20you%20created.) as it wasnt mentioned by the previous reviewer that's why its marked as optional but it would be nice to implement this 👍 

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)

Keep rocking 🚀!

2022-04-16 12:00 UTC, mmsesay approved these changes
Hi @KingsleyIbe & @Chimwemwe-127001,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-16 12:24 UTC, merged